name: fl_custom_image_view
description: A flexible Flutter widget for displaying images from multiple sources (network, assets, file, SVG, Lottie) with caching, placeholders, and customization options.
version: 1.0.1
homepage: https://github.com/flexioninfotech
repository: https://github.com/flexioninfotech/fl_custom_image_view
issue_tracker: https://github.com/flexioninfotech/fl_custom_image_view/issues
documentation: https://github.com/flexioninfotech/fl_custom_image_view/blob/main/README.md
topics:
  - flutter
  - image
  - cached-network-image
  - svg
  - lottie

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
